# syntax=docker/dockerfile:1
# check=error=true

# 手元で開発するためのDockerfile
# Rails標準のDockerfileを改変して作成
# docker compose up経由で起動されることを想定

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version
ARG RUBY_VERSION=3.4.6
FROM docker.io/library/ruby:$RUBY_VERSION-slim-trixie AS base

# Rails app lives here
WORKDIR /rails

# Install base packages
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y curl libjemalloc2 libvips sqlite3 python3.13 python3.13-venv python3.13-dev vim && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Create Python virtual environment
RUN python3.13 -m venv /opt/venv

# Set development environment
ENV BUNDLE_PATH="/usr/local/bundle" \
    VIRTUAL_ENV="/opt/venv" \
    PATH="/opt/venv/bin:$PATH"

# Install packages needed to build gems
# 開発用のDockerfileでは docker compose run --rm rails-app bundle install することがあるのでビルドに必要なパッケージは残しておく
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

# Throw-away build stage to reduce size of final image
FROM base AS build

# Install application gems
COPY Gemfile Gemfile.lock ./
RUN bundle install && \
    rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git && \
    bundle exec bootsnap precompile --gemfile

# Copy application code
# 実行時はホットリロードのため、docker-compose.yml側のvolumesで上書きされることを期待している
COPY . .




# Final stage for app image
FROM base

# Copy built artifacts: gems, application
COPY --from=build "${BUNDLE_PATH}" "${BUNDLE_PATH}"
COPY --from=build /rails /rails

# Run and own only the runtime files as a non-root user for security
RUN groupadd --system --gid 1000 rails && \
    useradd rails --uid 1000 --gid 1000 --create-home --shell /bin/bash && \
    chown -R rails:rails db log storage tmp && \
    chown -R rails:rails "${BUNDLE_PATH}" && \
    chown -R rails:rails /opt/venv
USER 1000:1000

# auto-red-team-promptのPython依存パッケージをインストール
# TODO: ビルドステージへ分離して、必要な成果物だけを含めるようにする
RUN CXXFLAGS="-Wno-error=free-nonheap-object" pip install ./auto-red-team-prompt --resume-retries=20

# Entrypoint prepares the database.
ENTRYPOINT ["/rails/bin/docker-entrypoint"]

# Start server
EXPOSE 3000
CMD ["bin/dev"]
