services:
  rails-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails:cached
    environment:
      - RAILS_ENV=development
      - BINDING=0.0.0.0
    env_file:
      - .env

