# Move this require to your `config/application.rb` if you want to be notified from runner commands too.
require "exception_notification/rails"
require "exception_notification/rake"


ExceptionNotification.configure do |config|
  # Ignore additional exception types. The default list of exception classes is:
  #   ActiveRecord::RecordNotFound Mongoid::Errors::DocumentNotFound AbstractController::ActionNotFound
  #   ActionController::RoutingError ActionController::UnknownFormat ActionController::UrlGenerationError
  #   ActionDispatch::Http::MimeNegotiation::InvalidType Rack::Utils::InvalidParameterError
  # config.ignored_exceptions += %w[ActionView::TemplateError CustomError]

  # Adds a condition to decide when an exception must be ignored or not.
  # The ignore_if method can be invoked multiple times to add extra conditions.
  # config.ignore_if do |exception, options|
  #   Rails.env.local?
  # end

  # Ignore exceptions generated by crawlers
  # config.ignore_crawlers %w[Googlebot bingbot]

  # Notifiers =================================================================

  # Slack notifier sends notifications to your Slack channel.
  # NOTE: ENV.fetch で nil をデフォにしないと、docker compose build の precompile で呼ばれて build ができない羽目に陥る
  webhook_url = Rails.env.production? ? ENV.fetch("SLACK_WEBHOOK_URL", nil) : ENV["SLACK_WEBHOOK_URL"]

  if webhook_url.present?
    config.add_notifier :slack, {
      webhook_url: webhook_url,
      channel: ENV.fetch("SLACK_CHANNEL", "#errors"),
      additional_fields: [
        { title: "Environment", value: Rails.env, short: true }
      ],
      additional_parameters: {
        mrkdwn: true
      }
    }
  end
end
