"""攻撃プロンプトに対して、LLM の応答を作成し、それを Constitution を考慮して改善させ、学習データを生成するスクリプト

応答作成の処理は `scripts/run_generate_response.py` に委譲しています。
"""

import argparse
import logging

from auto_red_teaming_prompt.generators.response_improve import ResponseImprover
from auto_red_teaming_prompt.utils.cli_logging import add_logging_args, init_logging_from_args
from auto_red_teaming_prompt.utils.common import initialize_llm


def get_args():
    """コマンドライン引数を解析します。"""
    parser = argparse.ArgumentParser(
        description="Generate training data by improving LLM responses using Constitution."
    )
    parser.add_argument(
        "--generator_output_file",
        type=str,
        required=True,
        help="Path to the JSON file containing responses generated by the response generator.",
    )
    parser.add_argument(
        "--constitution_file",
        type=str,
        required=True,
        help="Path to the Constitution file (text format).",
    )
    parser.add_argument(
        "--model_type",
        type=str,
        default="vllm",
        help="Type of language model to use (default: vllm)",
    )
    parser.add_argument(
        "--model_config_file",
        type=str,
        required=True,
        help="Path to the model configuration file (JSON format).",
    )
    parser.add_argument(
        "--output_file",
        type=str,
        default="generated_training_data.json",
        help="Path to save the generated training data (default: generated_training_data.json)",
    )
    # Logging options (common)
    add_logging_args(parser)

    return parser.parse_args()


def main():
    """作成した応答と Constitution から、学習データとして適切な応答を生成し、結果を保存するメイン関数。"""
    args = get_args()

    # Configure logging for CLI
    level = init_logging_from_args(args)
    logging.getLogger(__name__).debug("Initialized logging with level %s", level)

    llm = initialize_llm(args.model_type, args.model_config_file)
    generator = ResponseImprover(llm)

    original_data = generator.load_data(args.generator_output_file, args.constitution_file)
    output = generator.generate(original_data)
    generator.save_results(output, args.output_file)


if __name__ == "__main__":
    main()
